language: java

script:
  - ./gradlew clean assemble

after_success:
  - echo $TRAVIS_BRANCH
  - echo TRAVIS_PULL_REQUEST
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./gradlew bintrayUpload; fi


branches:
  only:
  - master
  
